apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fei9o0q0i-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/fei9o0q0i-java-quarkus-gitops